version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list
  build:
    desc: "Build the Swift application (macOS)"
    cmds:
      - swift build -c release

  run:
    desc: "Run the OpenPubkeyAgent executable (macOS)"
    deps: [build]
    cmds:
      - ./.build/release/OpenPubkeyAgent